// AUTO-GENERATED from Master Crash Report 1-266. Do not hand-edit.
export const CRASH_TOTAL = 266;
export const CRASH_LIST = [
  {no:1,category:"User/Session",name:"Visitors/Sessions blocked",reason:"Ad-blocker/localStorage disabled breaks AuthContext persist",signal:"userId, sessionId"},
  {no:2,category:"User/Session",name:"User journey break",reason:"Deep link /gallery/:slug without ?app=1 hits OG rewrite /api/gallery -> blank",signal:"route, slug"},
  {no:3,category:"User/Session",name:"Stale deploy chunk",reason:"Cached dist/assets + new deploy = Failed to fetch dynamic module",signal:"appVersion, chunk"},
  {no:4,category:"User/Session",name:"Geography/CDN block",reason:"R2 public URL / Fonts blocked by region",signal:"geo, ttfb"},
  {no:5,category:"User/Session",name:"Browser quirks",reason:"Safari WebGL2/HEIC/HLS/page-flip differences",signal:"browser/version"},
  {no:6,category:"User/Session",name:"Low-end device OOM",reason:"three+framer+masonry 1000 photos kills tab",signal:"deviceMemory, heap"},
  {no:7,category:"User/Session",name:"iOS OS behavior",reason:"100vh, PWA fullscreen, file picker accept",signal:"os, viewport"},
  {no:8,category:"User/Session",name:"Clock skew",reason:"Expired presigned R2 URL / JWT exp -> 403 loop",signal:"exp, serverTime"},
  {no:9,category:"User/Session",name:"Locale/Timezone",reason:"formatCoverDate Invalid Date, groupByMonth fail",signal:"locale, value"},
  {no:10,category:"User/Session",name:"Private mode quota",reason:"localStorage/IndexedDB QuotaExceededError",signal:"storageError"},
  {no:11,category:"User/Session",name:"Multi-tab session race",reason:"Logout in tab A, tab B saves with stale JWT",signal:"sessionId, authEvent"},
  {no:12,category:"User/Session",name:"Referral/deep-link loss",reason:"Custom domain vs pixnxt.in origin mismatch loses slug",signal:"origin, host"},
  {no:13,category:"Frontend",name:"Env boot fail",reason:"Missing VITE_SUPABASE_URL/R2_PUBLIC_URL -> white screen",signal:"envKey"},
  {no:14,category:"Frontend",name:"Route param crash",reason:"Invalid :slug, no ErrorBoundary -> App unmount",signal:"route, componentStack"},
  {no:15,category:"Frontend",name:"LCP/CLS/INP",reason:"50MB cover, no placeholder, masonry reflow",signal:"lcp, cls, inp"},
  {no:16,category:"Frontend",name:"JS TypeError",reason:"sortDashboardPhotos/filterClientGallerySearch on null",signal:"stack"},
  {no:17,category:"Frontend",name:"React key/dup render",reason:"Duplicate keys, setState during render, Suspense no fallback",signal:"componentStack"},
  {no:18,category:"Frontend",name:"Unhandled exception",reason:"exifr.parse, JSON.parse(localStorage) corrupt",signal:"error.message"},
  {no:19,category:"Frontend",name:"Unhandled promise",reason:"supabase select / photoAiSearch no catch/abort",signal:"promise, endpoint"},
  {no:20,category:"Frontend",name:"Blank screen boot",reason:"main.jsx provider throw, no boundary per route",signal:"boundaryCaught"},
  {no:21,category:"Frontend",name:"Chunk/resource 404",reason:"Vercel redeploy chunk mismatch, MIME text/html for JS",signal:"chunk, status"},
  {no:22,category:"Frontend",name:"R2 CORS CSS/JS/img fail",reason:"r2-cors-policy wrong, tailwind purge",signal:"cors, url"},
  {no:23,category:"Frontend",name:"StrictMode double effect",reason:"Double upload/fetch in dev",signal:"effect, reqId"},
  {no:24,category:"Frontend",name:"Three.js WebGL lost",reason:"@react-three/fiber/drei shader fail, context lost",signal:"webgl.supported"},
  {no:25,category:"Frontend",name:"Animation block",reason:"framer-motion/react-spring/lottie bad JSON blocks main",signal:"fps, longTask"},
  {no:26,category:"Frontend",name:"Font/icon fail",reason:"lucide dynamic import, custom font CORS",signal:"url"},
  {no:27,category:"Frontend",name:"Infinite render loop",reason:"useGalleryPeople/useCollectionDashboard/galleryLiveSync deps",signal:"renderCount"},
  {no:28,category:"Frontend",name:"ErrorBoundary missing",reason:"pages/* throw escapes to blank",signal:"route"},
  {no:29,category:"Frontend",name:"Realtime resub loop",reason:"galleryLiveSync reconnect burns quota",signal:"realtimeStatus"},
  {no:30,category:"Frontend",name:"PWA manifest/icon 404",reason:"/m/:slug/manifest rewrites fail -> install crash",signal:"manifestStatus"},
  {no:31,category:"Interaction",name:"Double-click action",reason:"Upload/Delete/Share duplicate req 409",signal:"doubleClick"},
  {no:32,category:"Interaction",name:"Form no-validate",reason:"Supabase check constraint fail",signal:"payload"},
  {no:33,category:"Interaction",name:"Login/Signup/Logout loop",reason:"googleAuthExchange state mismatch, stale session",signal:"oauthState"},
  {no:34,category:"Interaction",name:"Search regex freeze",reason:"filterClientGallerySearch /[.*+/ 10k rows blocks UI",signal:"query, ms"},
  {no:35,category:"Interaction",name:"Upload burst",reason:"500 files, 0-byte/HEIC/RAW unsupported",signal:"fileCount, mime"},
  {no:36,category:"Interaction",name:"Zip download OOM",reason:"JSZip 2GB, file-saver blob leak",signal:"sizeBytes"},
  {no:37,category:"Interaction",name:"Copy/Delete/Share race",reason:"Optimistic delete then API fail -> ghost UI",signal:"targetId"},
  {no:38,category:"Interaction",name:"Back during upload",reason:"fetch AbortError unhandled",signal:"abortReason"},
  {no:39,category:"Interaction",name:"Modal/focus trap",reason:"fullscreenUtils, react-easy-crop leak, Esc mid-transition",signal:"modalId"},
  {no:40,category:"Interaction",name:"Drag & drop null ref",reason:"@dnd-kit sortable virtualized + touch conflict",signal:"dndId"},
  {no:41,category:"Interaction",name:"Crop/Watermark tainted",reason:"canvas toDataURL CORS throw",signal:"coverUrl"},
  {no:42,category:"Interaction",name:"Zoom/Pan/Flipbook",reason:"react-pageflip/use-gesture pinch throw touch",signal:"gesture"},
  {no:43,category:"Interaction",name:"Shortcut while typing",reason:"Delete key deletes album while in input",signal:"focusedElement"},
  {no:44,category:"Interaction",name:"Star/Hide race",reason:"star+hide last-write-wins flicker",signal:"photoId"},
  {no:45,category:"Interaction",name:"Move/Copy stale folder",reason:"folder deleted elsewhere 23503 modal stuck",signal:"folder_id"},
  {no:46,category:"Interaction",name:"QR share dead",reason:"api.qrserver.com down -> image 404",signal:"qrUrl"},
  {no:47,category:"API",name:"Wrong method/path",reason:"/api/r2-upload/r2-media/photo-ai/guest-delivery 405",signal:"method, endpoint"},
  {no:48,category:"API",name:"4xx vs 5xx mix",reason:"No distinction client-fix vs page",signal:"status"},
  {no:49,category:"API",name:"P50/P95/P99 slow",reason:"Rekognition 8s, R2 list 5s -> Vercel 10/60s timeout",signal:"latency"},
  {no:50,category:"API",name:"No AbortController",reason:"devApiMiddleware hang, client never aborts",signal:"durationMs"},
  {no:51,category:"API",name:"400 bad slug",reason:"Unencoded slug decodeURIComponent URIError",signal:"slug"},
  {no:52,category:"API",name:"401/403 auth",reason:"No JWT / RLS deny / presigned expiry",signal:"role"},
  {no:53,category:"API",name:"404 slug gone",reason:"Deleted delivery still linked in email",signal:"slug"},
  {no:54,category:"API",name:"413 too large",reason:"No client pre-check before PUT",signal:"sizeBytes"},
  {no:55,category:"API",name:"429 throttled",reason:"photo-ai/rekognition no limit -> bill spike",signal:"retryCount"},
  {no:56,category:"API",name:"500 sharp fail",reason:"Unsupported format resize throw",signal:"mime"},
  {no:57,category:"API",name:"502 upload handler",reason:"handleR2Upload throw",signal:"r2Key"},
  {no:58,category:"API",name:"503 Supabase down",reason:"Pooler too many clients",signal:"pgCode"},
  {no:59,category:"API",name:"504 OG cover timeout",reason:"/gallery/:slug cover.jpg sharp timeout",signal:"slug"},
  {no:60,category:"API",name:"Path traversal",reason:"?path=users/../../ not sanitized",signal:"path"},
  {no:61,category:"API",name:"CORS preflight PUT",reason:"Content-Type mismatch presign",signal:"cors"},
  {no:62,category:"API",name:"No idempotency",reason:"Retry creates duplicate rows",signal:"Idempotency-Key"},
  {no:63,category:"CrashType",name:"Frontend crash",reason:"No per-route boundary",signal:"fatal"},
  {no:64,category:"CrashType",name:"Backend crash",reason:"r2Upload/r2MediaProxy uncaught await",signal:"endpoint"},
  {no:65,category:"CrashType",name:"Worker crash",reason:"pdfjs worker 404, sharp ABI missing",signal:"worker"},
  {no:66,category:"CrashType",name:"API validation leak",reason:"err.message exposes internals",signal:"error"},
  {no:67,category:"CrashType",name:"DB RLS deny",reason:"mobileGalleryDbError swallowed",signal:"pgCode 42501"},
  {no:68,category:"CrashType",name:"Network offline",reason:"Failed to fetch, DNS R2",signal:"online"},
  {no:69,category:"CrashType",name:"Auth expired",reason:"JWT/refresh revoked loop",signal:"exp"},
  {no:70,category:"CrashType",name:"AuthZ IDOR",reason:"Change slug accesses other album",signal:"slug, userId"},
  {no:71,category:"CrashType",name:"Timeout hang",reason:"HLS stall, OG sharp block",signal:"durationMs"},
  {no:72,category:"CrashType",name:"OOM/heap",reason:"JS heap, WebGL memory",signal:"heapUsed"},
  {no:73,category:"CrashType",name:"Stack overflow",reason:"Recursive sortFolders/groupByMonth cyclic",signal:"stack"},
  {no:74,category:"CrashType",name:"Quota 5MB",reason:"localStorage/IndexedDB/R2/Supabase row limit",signal:"quota"},
  {no:75,category:"CrashType",name:"SDK throw",reason:"lib-storage multipart abort, realtime disconnect",signal:"sdk"},
  {no:76,category:"CrashType",name:"Flag undefined",reason:"collectionFeatureFlags/clientExclusiveAccess gate crash",signal:"flag"},
  {no:77,category:"CrashType",name:"Unhandled exception",reason:"Missing window.onerror reporter",signal:"stack"},
  {no:78,category:"CrashType",name:"Unhandled rejection",reason:"Missing unhandledrejection reporter",signal:"promise"},
  {no:79,category:"CrashType",name:"Paused-share fake",reason:"localStorage overlay faked PAUSED while open",signal:"share_link_enabled"},
  {no:80,category:"CrashType",name:"Orphan file/row",reason:"R2 deleted but DB row remains (or inverse)",signal:"r2Key, photoId"},
  {no:81,category:"Supabase-Migrate",name:"collections vs deliveries",reason:"photo_ai_metadata REFERENCES collections VIEW; DROP CASCADE 42P01",signal:"pgCode, table"},
  {no:82,category:"Supabase-Migrate",name:"smart_albums vs album_proofer",reason:"Old name query PGRST205",signal:"table"},
  {no:83,category:"Supabase-Migrate",name:"Manual photographer cols",reason:"update_photographers_table.sql not migrated 42703",signal:"column"},
  {no:84,category:"Supabase-Migrate",name:"Enum rename",reason:"collection_status->delivery_status 42704",signal:"enum"},
  {no:85,category:"Supabase-Migrate",name:"Missing NOTIFY pgrst",reason:"PostgREST stale cache 404",signal:"migration"},
  {no:86,category:"Supabase-Migrate",name:"VIEW collections no RLS",reason:"GRANT SELECT anon bypasses deliveries intent",signal:"role"},
  {no:87,category:"Supabase-Migrate",name:"Index rename missing",reason:"Old index name cleanup fails deploy",signal:"index"},
  {no:88,category:"Supabase-Migrate",name:"Cover focal type fix",reason:"center vs center_ drift CHECK fail",signal:"value"},
  {no:89,category:"Supabase-Migrate",name:"Thumbnail enum small",reason:"x-small->small round-trip drift",signal:"thumbnail_size"},
  {no:90,category:"Supabase-Migrate",name:"Watermark enum",reason:"position enum mismatch save loop",signal:"watermark"},
  {no:91,category:"Supabase-RLS",name:"Comment recursion 42P17",reason:"Policy selects self; fixed via SECURITY DEFINER helper",signal:"policy"},
  {no:92,category:"Supabase-RLS",name:"Anon published only old table",reason:"QR link 0 rows blank gallery",signal:"role, slug"},
  {no:93,category:"Supabase-RLS",name:"photos owner-only",reason:"Guest needs published_deliveries policy or blank",signal:"role"},
  {no:94,category:"Supabase-RLS",name:"event_guests no anon INSERT",reason:"Direct insert 42501; must use service_role API",signal:"role"},
  {no:95,category:"Supabase-RLS",name:"download_jobs NULL owner",reason:"SET NULL orphan disappears",signal:"jobId"},
  {no:96,category:"Supabase-RLS",name:"store_packages anon enumerate",reason:"is_active=true readable by all",signal:"table"},
  {no:97,category:"Supabase-RLS",name:"admins check missing uid",reason:"Any auth reads photographers",signal:"policy"},
  {no:98,category:"Supabase-RLS",name:"Service key in client",reason:"VITE_ mistake bypass then breaks on rotate",signal:"envKey"},
  {no:99,category:"Supabase-RLS",name:"Custom domain public read",reason:"Unverified domain photographer leak",signal:"domain"},
  {no:100,category:"Supabase-RLS",name:"Sets/photos anon join",reason:"Missing sets_in_published_deliveries -> empty set",signal:"slug"},
  {no:101,category:"Supabase-Constr",name:"UNIQUE download_token",reason:"Double-click 23505 must be idempotent success",signal:"constraint"},
  {no:102,category:"Supabase-Constr",name:"UNIQUE photographer+slug",reason:"Duplicate slug 23505 -> /gallery/undefined",signal:"slug"},
  {no:103,category:"Supabase-Constr",name:"UNIQUE guest slug GLOBAL",reason:"Two studios same slug collision",signal:"slug"},
  {no:104,category:"Supabase-Constr",name:"UNIQUE event+email/access_token",reason:"Retry resend 23505 double link",signal:"email"},
  {no:105,category:"Supabase-Constr",name:"UNIQUE guest+photo",reason:"Republish duplicate match 23505",signal:"guest_id"},
  {no:106,category:"Supabase-Constr",name:"UNIQUE photo_ai photo_id",reason:"Reindex race 23505",signal:"photo_id"},
  {no:107,category:"Supabase-Constr",name:"CASCADE delete fan-out",reason:"Delete delivery cascades photos/jobs timeout + R2 orphan",signal:"deliveryId"},
  {no:108,category:"Supabase-Constr",name:"SET NULL orphan",reason:"NULL photographer/folder ghost NaN quota",signal:"photoId"},
  {no:109,category:"Supabase-Constr",name:"CHECK status enums",reason:"archived vs draft/published 23514 spinner hang",signal:"status"},
  {no:110,category:"Supabase-Constr",name:"CHECK photo_count/price",reason:"0 / negative 23514",signal:"value"},
  {no:111,category:"Supabase-Constr",name:"NOT NULL visitor/file fields",reason:"Missing email/storage_path job stuck pending",signal:"field"},
  {no:112,category:"Supabase-Constr",name:"5GB bucket limit",reason:"gallery-downloads file_size_limit exceeded",signal:"sizeBytes"},
  {no:113,category:"Supabase-Constr",name:"Storage recalc per-row",reason:"tr_recalculate_storage 500x SUM lock timeout",signal:"photographer_id"},
  {no:114,category:"Supabase-Constr",name:"r2_folder collision",reason:"john@gmail + john@yahoo -> users/john overwrite",signal:"r2_folder"},
  {no:115,category:"Supabase-Constr",name:"Match FK photo deleted",reason:"Face modal null URL crash",signal:"photo_id"},
  {no:116,category:"Supabase-Query",name:"N+1 gallery open",reason:"1 delivery + N photos/ai no pagination P95>5s",signal:"latencyMs"},
  {no:117,category:"Supabase-Query",name:"Missing composite index",reason:"(collection_id,position) sort slow",signal:"query"},
  {no:118,category:"Supabase-Query",name:"Realtime no REPLICA FULL",reason:"galleryLiveSync delete null old row removes wrong",signal:"realtime"},
  {no:119,category:"Supabase-Query",name:"Private bucket direct read",reason:"gallery-downloads anon 403; need signed URL",signal:"bucket"},
  {no:120,category:"Supabase-Query",name:"Token leak no rotation",reason:"/download/:token forwarded, no expiry check",signal:"token"},
  {no:121,category:"Supabase-Query",name:"Edge secrets missing",reason:"PUBLIC_SITE_URL/VERCEL_TOKEN/AWS/SMTP missing 500",signal:"secret"},
  {no:122,category:"Supabase-Query",name:"Cron pg_cron off",reason:"Expiry/album reminders never fire or duplicate",signal:"cron"},
  {no:123,category:"Supabase-Query",name:"Pooler exhaustion",reason:"Realtime+SSR+edge too many clients",signal:"poolUsed"},
  {no:124,category:"Files",name:"Multipart abort mid-upload",reason:"S3 SlowDown/signature mismatch partial R2",signal:"multipartId"},
  {no:125,category:"Files",name:"Presigned expired download",reason:"Range unsupported 403 loop",signal:"r2Key"},
  {no:126,category:"Files",name:"DB/R2 out of sync",reason:"Delete one side leaves broken image",signal:"photoId"},
  {no:127,category:"Files",name:"Bad filename encode",reason:"emoji/unicode/#? URIError via proxy",signal:"fileName"},
  {no:128,category:"Files",name:"0-byte upload",reason:"size_bytes NULL quota NaN",signal:"sizeBytes"},
  {no:129,category:"Files",name:"100MB RAW main-thread",reason:"exifr+imageDimensions freeze",signal:"mime"},
  {no:130,category:"Files",name:"Corrupt EXIF",reason:"exifr/rawImageFormats throw",signal:"exifError"},
  {no:131,category:"Files",name:"Undecodable image",reason:"CMYK/HEIC Safari broken icon",signal:"mime"},
  {no:132,category:"Files",name:"HLS manifest/codec",reason:"m3u8 404/CORS stall",signal:"videoId"},
  {no:133,category:"Files",name:"PDF encrypted/500p",reason:"pdfjs OOM",signal:"pages"},
  {no:134,category:"Files",name:"Zip name too long Win",reason:"JSZip generateAsync OOM",signal:"zipName"},
  {no:135,category:"Files",name:"sharp EMFILE/format",reason:"Too many files / unsupported",signal:"mime"},
  {no:136,category:"Files",name:"Google Drive quota",reason:"drive rateLimit/token mid-upload",signal:"driveError"},
  {no:137,category:"Files",name:"No resume/progress",reason:"Large HLS/zip duration unknown fail",signal:"durationMs"},
  {no:138,category:"Files",name:"Thumbnail null cover",reason:"cover_url null OG 500",signal:"slug"},
  {no:139,category:"Security",name:"WAF false positive",reason:"?path= blocked",signal:"wafAction"},
  {no:140,category:"Security",name:"OG DDoS expensive",reason:"/gallery/:slug?action=og sharp no cache",signal:"ip, slug"},
  {no:141,category:"Security",name:"Slug enumeration bot",reason:"/gallery/1..10000 scrape",signal:"ip, ua"},
  {no:142,category:"Security",name:"No rate limit AI",reason:"photo-ai/rekognition bill spike",signal:"rateLimitHit"},
  {no:143,category:"Security",name:"XSS album title",reason:"dangerouslySetInnerHTML stored script",signal:"field"},
  {no:144,category:"Security",name:"SQLi search",reason:"Unescaped search in RPC",signal:"query"},
  {no:145,category:"Security",name:"IDOR slug swap",reason:"Other studio album access",signal:"slug, userId"},
  {no:146,category:"Security",name:"Mass download IP",reason:"r2-media?path= bulk",signal:"ip"},
  {no:147,category:"Security",name:"Signed URL forwarded",reason:"No expiry/password/pause bypass",signal:"token"},
  {no:148,category:"Security",name:"CORS * hotlink",reason:"Any site embeds R2",signal:"origin"},
  {no:149,category:"Security",name:"Secret bundled VITE_",reason:"SERVICE_KEY in client",signal:"envKey"},
  {no:150,category:"Security",name:"Upload .html/.svg/.js",reason:"Stored XSS when served",signal:"mime"},
  {no:151,category:"Perf",name:"3MB Three always loaded",reason:"No route split LCP bad",signal:"bundleSize"},
  {no:152,category:"Perf",name:"No cache preview/share/icon",reason:"albumPreview/galleryShare/m/icon miss",signal:"cacheStatus"},
  {no:153,category:"Perf",name:"Cold start chain",reason:"Vercel+Supabase+Rekognition cold TTFB",signal:"ttfb"},
  {no:154,category:"Perf",name:"sharp sync block",reason:"Resize blocks loop",signal:"cpuMs"},
  {no:155,category:"Perf",name:"O(n2) sort/search",reason:"faceAvatarMath/photoAiSearch/masonry",signal:"cpuMs"},
  {no:156,category:"Perf",name:"Image cache stale",reason:"photoAiCacheFreshness no SWR",signal:"cacheStatus"},
  {no:157,category:"Perf",name:"No srcset mobile",reason:"Full-res to phone bandwidth",signal:"bytes"},
  {no:158,category:"Perf",name:"R2 origin slow",reason:"No CDN TTFB",signal:"ttfb"},
  {no:159,category:"Perf",name:"Slow endpoints top",reason:"rekognition/r2-upload/og",signal:"p50/p95/p99"},
  {no:160,category:"Perf",name:"createObjectURL leak",reason:"Never revoked + three dispose miss",signal:"heapUsed"},
  {no:161,category:"Perf",name:"Main chunk heavy",reason:"pdfjs+three+hls+jszip together",signal:"bundleSize"},
  {no:162,category:"Perf",name:"Build OOM sharp",reason:"Vercel native ABI/type error CI only",signal:"buildLog"},
  {no:163,category:"Perf",name:"SW stale loop",reason:"Old SW serves deleted chunk",signal:"swVersion"},
  {no:164,category:"Build",name:"Bad .env swap",reason:"vercel.app URL as PUBLIC_SITE_URL breaks QR",signal:"envKey"},
  {no:165,category:"Build",name:"vercel.json order",reason:"((?!api/).*) before /api/ loops to index.html",signal:"route"},
  {no:166,category:"Build",name:"Node ABI sharp",reason:"Node 20 vs 22 native fail",signal:"nodeVer"},
  {no:167,category:"Build",name:"eslint blocks deploy",reason:"Unused import fails build",signal:"lint"},
  {no:168,category:"Auth",name:"useAuth race",reason:"accountSessions multi-tab stale",signal:"userId"},
  {no:169,category:"Auth",name:"OAuth state mismatch",reason:"sessionStorage cleared, callback 400",signal:"oauthState"},
  {no:170,category:"Auth",name:"User deleted orphans",reason:"FK photos/R2 left, gallery 500",signal:"userId"},
  {no:171,category:"Deps",name:"react19 vs pageflip2",reason:"Peer break flipbook crash",signal:"depVer"},
  {no:172,category:"Deps",name:"lucide breaking",reason:"Icon import null",signal:"depVer"},
  {no:173,category:"Deps",name:"hls regression",reason:"Version bump stalls",signal:"depVer"},
  {no:174,category:"PWA",name:"Install prompt twice",reason:"InvalidStateError iOS dead button",signal:"platform"},
  {no:175,category:"PWA",name:"Standalone safe-area",reason:"Buttons under notch unclickable",signal:"viewport"},
  {no:176,category:"State",name:"uploadQueue stuck",reason:"Context queue never drains after fail",signal:"queueLen"},
  {no:177,category:"State",name:"Corrupt persisted JSON",reason:"albumLocalStorage/designSettings crash boot",signal:"storageKey"},
  {no:178,category:"State",name:"Stale closure revert",reason:"Package toggle reverts to stale not server",signal:"toggleKey"},
  {no:179,category:"UI-Button",name:"Domain Verify double",reason:"2x verify 23505 busy bypass overlay",signal:"buttonId"},
  {no:180,category:"UI-Button",name:"Preset/Expiry/Watermark spam",reason:"No disabled duplicate reminders",signal:"buttonId"},
  {no:181,category:"UI-Button",name:"Pause fake closed",reason:"paused_at null vs false leak open",signal:"share_link_enabled"},
  {no:182,category:"UI-Button",name:"Cancel mid-multipart",reason:"R2 part + NULL size row",signal:"photoId"},
  {no:183,category:"UI-Button",name:"Optimistic delete ghost",reason:"23503 already removed undefined",signal:"targetId"},
  {no:184,category:"UI-Button",name:"Clipboard denied custom domain",reason:"Non-HTTPS throw uncaught",signal:"origin"},
  {no:185,category:"UI-Button",name:"Back/Next/X mid-fetch",reason:"AbortError draft lost",signal:"modalStep"},
  {no:186,category:"UI-Button",name:"PWA null prompt",reason:"No fallback instructions",signal:"platform"},
  {no:187,category:"UI-Field",name:"Domain paste with protocol",reason:"www alias checks only [0] pending forever",signal:"domainDraft"},
  {no:188,category:"UI-Field",name:"Slug emoji/long/dup",reason:"undefined route blank",signal:"slug"},
  {no:189,category:"UI-Field",name:"Bad email cached",reason:"Auto-login loop 0 rows",signal:"visitor_email"},
  {no:190,category:"UI-Field",name:"Password no limit",reason:"Back-nav unlocks locked view",signal:"collectionId"},
  {no:191,category:"UI-Field",name:"RichText script paste",reason:"Stored XSS client gallery",signal:"html"},
  {no:192,category:"UI-Field",name:"Expiry PIN null",reason:"Edge 500 retry spam",signal:"pin"},
  {no:193,category:"UI-Field",name:"Watermark 0/200 unclamped",reason:"sharp composite crash tainted",signal:"watermark"},
  {no:194,category:"UI-Field",name:"Price/count string",reason:"CHECK 23514 hang",signal:"price"},
  {no:195,category:"UI-Field",name:"Enquiry field deleted live",reason:"JSONB missing NOT NULL hang",signal:"field"},
  {no:196,category:"UI-Field",name:"Search regex throw",reason:"Unescaped freeze main",signal:"query"},
  {no:197,category:"UI-Toggle",name:"Share flags local-first leak",reason:"OFF shown DB ON public leak",signal:"share_link_enabled"},
  {no:198,category:"UI-Toggle",name:"Slideshow fallback split",reason:"Local vs DB tabs disagree flicker",signal:"slideshow_enabled"},
  {no:199,category:"UI-Toggle",name:"Exclusive access stale key",reason:"Wrong client sees private",signal:"collectionId"},
  {no:200,category:"UI-Toggle",name:"400ms debounce collapse",reason:"ON-OFF-ON loses middle DB!=UI",signal:"toggleKey"},
  {no:201,category:"UI-Toggle",name:"Package stale revert",reason:"Inverted stuck",signal:"packageId"},
  {no:202,category:"UI-Toggle",name:"24 notif local only",reason:"New device all ON misses alert",signal:"settingKey"},
  {no:203,category:"UI-Toggle",name:"All folders unchecked",reason:"Showcase [] drag OOB",signal:"folder_id"},
  {no:204,category:"UI-Toggle",name:"Select round-trip drift",reason:"tight->regular every save",signal:"grid_spacing"},
  {no:205,category:"UI-Toggle",name:"Admin switch no confirm",reason:"Double-activate promote audit dup",signal:"userId"},
  {no:206,category:"UI-Toggle",name:"iOS double-fire",reason:"Parent+input both flip",signal:"toggleKey"},
  {no:207,category:"UI-Save",name:"updateProfile before confirm",reason:"Failed save shows saved + alert blocks",signal:"profileId"},
  {no:208,category:"UI-Save",name:"Upload defaults string bug",reason:"sharpen_for_web 'false' truthy RAW wrong",signal:"settingKey"},
  {no:209,category:"UI-Save",name:"Showcase silent invisible",reason:"Disabled page still advertised 404",signal:"showcase_enabled"},
  {no:210,category:"UI-Save",name:"Modal closes pre-await",reason:"Rejected item shown duplicates on reopen",signal:"modalId"},
  {no:211,category:"UI-Domain",name:"Wrong CNAME env",reason:"Wrong DNS table",signal:"cnameTarget"},
  {no:212,category:"UI-Domain",name:"Cloudflare proxied",reason:"Orange cloud verify fail",signal:"domain"},
  {no:213,category:"UI-Domain",name:"Apex missing @ A",reason:"Root down",signal:"domain"},
  {no:214,category:"UI-Domain",name:"No VERCEL_TOKEN",reason:"DNS ok SSL never pending forever",signal:"domain"},
  {no:215,category:"UI-Domain",name:"www vs bare alias",reason:"Only [0] checked false pending",signal:"domain"},
  {no:216,category:"UI-Domain",name:"Unverified host images 403",reason:"r2MediaProxy/publicSiteUrl wrong origin",signal:"originHost"},
  {no:217,category:"UI-Domain",name:"Remove no Vercel detach",reason:"Deleted studio route hijack",signal:"domain"},
  {no:218,category:"Send",name:"Share send/schedule",reason:"SMTP 503 + local fallback fake Sent log",signal:"recipient"},
  {no:219,category:"Send",name:"Expiry email+WA toggle",reason:"Empty to_whatsapp skip + raw {vars}",signal:"reminderId"},
  {no:220,category:"Send",name:"Favorite submit spam",reason:"RPC 0 but email fires",signal:"listId"},
  {no:221,category:"Send",name:"Selection choose 404 link",reason:"Unverified domain dead link no log",signal:"slug"},
  {no:222,category:"Send",name:"Proofer proof/reminder open-paused",reason:"Link open when paused RLS 42501",signal:"albumId"},
  {no:223,category:"Send",name:"Comment parent deleted",reason:"Email links missing spread crash",signal:"commentId"},
  {no:224,category:"Send",name:"Guest token collision",reason:"2 links old 404",signal:"guestId"},
  {no:225,category:"Send",name:"Mobile invite localhost",reason:"localhost link to client",signal:"appId"},
  {no:226,category:"Send",name:"Store test prompt null",reason:"Esc must abort; bad phone wa.me fail",signal:"recipient"},
  {no:227,category:"Send",name:"Store bulk partial success",reason:"Shown as full success alert",signal:"campaignId"},
  {no:228,category:"Send",name:"Order charged no email",reason:"SMTP fail no retry queue",signal:"orderId"},
  {no:229,category:"Send",name:"Referral self/dup",reason:"No unique guard double credit",signal:"email"},
  {no:230,category:"Send",name:"Digest double notify",reason:"Realtime+email spam mark",signal:"albumId"},
  {no:231,category:"Send",name:"Gmail/wa.me client-only leak",reason:"?cid= draft leaked; >4000 chars cut; popup null",signal:"shareUrl"},
  {no:232,category:"Send",name:"Direct link bypass capture",reason:"Anon download unlogged quota undercount",signal:"slug"},
  {no:233,category:"Send",name:"Cover null broken img",reason:"Email <img> 404 spam score",signal:"coverUrl"},
  {no:234,category:"Send",name:"Theme preview mismatch",reason:"Different CSS client sees different",signal:"theme"},
  {no:235,category:"Send",name:"Password in share table",reason:"Plaintext in delivery_share_emails anon-readable",signal:"collectionId"},
  {no:236,category:"Btn-Global",name:"Topbar toggles/logout race",reason:"Overlap + half-cleared auth loop",signal:"panel"},
  {no:237,category:"Btn-Global",name:"Boundary Retry loop",reason:"Corrupt cache instant re-crash",signal:"route"},
  {no:238,category:"Btn-Global",name:"Command search stale slug",reason:"Deleted id blank",signal:"slug"},
  {no:239,category:"Btn-Dash",name:"Bulk with [] selection",reason:"Server 400 shared applying flag corrupt",signal:"bulkOp"},
  {no:240,category:"Btn-Dash",name:"Folder share stale URL",reason:"Renamed slug old link",signal:"folderId"},
  {no:241,category:"Btn-Collab",name:"Design save drift",reason:"tight/x-small round-trip",signal:"deliveryId"},
  {no:242,category:"Btn-Collab",name:"Cover focal unsaved",reason:"Slug drift autosave wrong recovery",signal:"slug"},
  {no:243,category:"Btn-Collab",name:"Set menu concurrent",reason:"Star during Move corrupt setId",signal:"setId"},
  {no:244,category:"Btn-Share",name:"Theme submenu stuck open",reason:"Outside click not closed picks wrong",signal:"theme"},
  {no:245,category:"Btn-Share",name:"Schedule past date",reason:"Edge accepts past -> immediate send marked Scheduled",signal:"scheduledAt"},
  {no:246,category:"Btn-Share",name:"History local vs DB split",reason:"localStorage email_history diverges DB",signal:"collectionId"},
  {no:247,category:"Btn-Guest",name:"Publish timeout half-write",reason:"Republish dup 23505",signal:"eventId"},
  {no:248,category:"Btn-Guest",name:"Copy link wrong env origin",reason:"localhost link in prod",signal:"origin"},
  {no:249,category:"Btn-Mobile",name:"Cover race 2 objects",reason:"Points to failed 404 manifest fail",signal:"appId"},
  {no:250,category:"Btn-Mobile",name:"Context menu off-screen",reason:"Delete tapped instead of Share",signal:"menuId"},
  {no:251,category:"Btn-Proofer",name:"Voice 5MB blow",reason:"localStorage quota breaks thread",signal:"albumId"},
  {no:252,category:"Btn-Proofer",name:"Restore overwrites new",reason:"No merge loses comments",signal:"spreadId"},
  {no:253,category:"Btn-Proofer",name:"Pin on deleted spread",reason:"FK 23503 toast loop",signal:"pinId"},
  {no:254,category:"Btn-Store",name:"Bulk price string",reason:"CHECK fail half saved",signal:"packageId"},
  {no:255,category:"Btn-Store",name:"Preview channel state leak",reason:"WhatsApp template shown in Email tab",signal:"campaignId"},
  {no:256,category:"Btn-Store",name:"Save address/order no confirm",reason:"Double charge on double-click",signal:"orderId"},
  {no:257,category:"Btn-Store",name:"Crop tainted save",reason:"toDataURL throw draft lost",signal:"artworkId"},
  {no:258,category:"Btn-Settings",name:"Logo R2 ok DB fail",reason:"Orphan + broken img",signal:"photographerId"},
  {no:259,category:"Btn-Settings",name:"Language select no persist",reason:"Reload reverts enquiry lang",signal:"locale"},
  {no:260,category:"Btn-Auth",name:"Google state lost tab close",reason:"Callback 400 no retry",signal:"oauthState"},
  {no:261,category:"Btn-Admin",name:"Promote no audit",reason:"Escalation invisible",signal:"userId"},
  {no:262,category:"Btn-Admin",name:"Ban self lockout",reason:"Admin bans own id no guard",signal:"userId"},
  {no:263,category:"Btn-Visitor",name:"Choose submit empty",reason:"0 photos RPC 0 but toast success",signal:"listId"},
  {no:264,category:"Btn-Visitor",name:"Download token reuse",reason:"Expired token page crash no resend",signal:"token"},
  {no:265,category:"Btn-Visitor",name:"Selfie search huge base64",reason:"/api/photo-ai 413 no compress",signal:"collectionId"},
  {no:266,category:"Btn-Visitor",name:"Enquiry double submit",reason:"Duplicate showcase_enquiries rows",signal:"enquiryId"},
];
export const crashByNo = (no) => CRASH_LIST.find((c)=>c.no===Number(no)) || {no,category:"Unknown",name:"Unknown crash",reason:"Unmapped",signal:""};
export const CRASH_CATEGORIES = [...new Set(CRASH_LIST.map((c)=>c.category))];